### PR TITLE
Update Childrens_Barnyard.md

### PR DESCRIPTION
**Pull request by kepm**

### CODE REVIEW

**Comment by kepm** [comment]
Hi James- 
When I was updating my pages I didn't notice any info for the Poultry Show. Is it there somewhere? Also the schedule of events and entry forms? Just let me know when I am able to update these as well. Thank you. 

-Pam Gevry

**Comment by jamesjnadeau** [comment]
Hi Pam,

The Poultry show is here:
https://www.addisoncountyfielddays.com/exhibits/poultry/

and the schedule is in the main nav:
https://www.addisoncountyfielddays.com/schedule/
(this one is formatted a little differently in the code, let me know if
you need help with the changes.

**Comment by kepm** [comment]
Hi James- 
I updated a couple more things this morning. I didn't see the ability to update the entry forms, are they there somewhere too? 
I still need to check on something with Wayne Marcelle for the Poultry show. 
-Also did I already update the Rabbit Show info? I'm having a moment as to whether I actually did or not. 

-- 
Pam Gevry 
Champlain Valley Farm/KEPM Trucking LLC 
h) 802-759-2238 
c) 802-373-8069

**Comment by jamesjnadeau** [comment]
Hi Pam,
The Entry forms need to be updated elsewhere and sent to me via email, They are currently in pdf form.

Here are the edits you made to the rabbit show already:
https://github.com/jamesjnadeau/addisoncountyfielddays/commit/bba0b159bdaa6a0dceb9707604cd78a987b98e5f#diff-e4d11a332c6d912cdc45908b37b18cffb612794e83fe5c32c38f20f7afd0b9f8R34-L40

**Comment by kepm** [comment]
Hi James- 
I looked over the following entry forms from 2019 and listed the changes below, because there is so few changes I figured it would be easiest for you to make them? 
Children's Barnyard & Educational Displays-Where it says age after name at the top please change that to "Youth Age____________" 
Rabbit Showmanship-I didn't even see this form online, but if you have it the only change to it would be to add "Age________" after Exhibitor Name. (I have attached a copy of it if you need an original) 
Egg Judging-no changes 
Poultry Exhibit/Showmanship-no changes 

I hopefully updated the schedule of events correctly, the two main things are to be sure the Rabbit Show is listed on Wednesday at 4:00 at the Children's Barnyard and the Poultry Show is on Saturday morning at 10:00 at the Children's Barnyard. 

I'm all set with the Poultry Show information that I had asked you to wait on also. I think that's everything for me! Phew! Let me know if you have any questions or need anything else from me. 

-Pam Gevry

**Comment by jamesjnadeau** [comment]
Hi Pam,

Please make these changes yourself, I don't have a way to edit a pdf.

The schedule of events looked good to me.

I believe the poultry edits are live, but let me know if you see
otherwise.

**Comment by kepm** [comment]
Hi- 
Attached is the Rabbit Show Entry Form with updates in pdf form. I don't have an original to the Children's Barnyard Entry Form but that's ok we will just use it as is. Thanks! 
-Pam

**Comment by jamesjnadeau** [comment]
Hi Pam, please email me directly, you're contacting me through github and your attahcments won't go through. My email is james.nadeau@gmail.com

**Pull request merged**
